# Generated by Django 5.2.14 on 2026-06-05 12:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertokenfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=accounts.models.user_avatar_upload_to),
        ),
    ]
