# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_avatar"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE users "
                        "ADD COLUMN IF NOT EXISTS avatar_url jsonb NOT NULL "
                        "DEFAULT '{}'::jsonb"
                    ),
                    reverse_sql="ALTER TABLE users DROP COLUMN IF EXISTS avatar_url",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="avatar_url",
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
        ),
    ]
