# Generated by Django 5.2.14 on 2026-06-01 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'authors',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('year_of_publication', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FormatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'format_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'publishers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'series',
                'db_table': 'series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.PROTECT, related_name='book_authors', to='catalog.author')),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='catalog.book')),
            ],
            options={
                'db_table': 'book_authors',
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='catalog.BookAuthor', to='catalog.author'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, related_name='book_categories', to='catalog.book')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='book_categories', to='catalog.category')),
            ],
            options={
                'db_table': 'book_categories',
                'unique_together': {('book', 'category')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', through='catalog.BookCategory', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(db_column='publisher_id', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.publisher'),
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.PositiveIntegerField()),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, related_name='book_series', to='catalog.book')),
                ('series', models.ForeignKey(db_column='series_id', on_delete=django.db.models.deletion.PROTECT, related_name='book_series', to='catalog.series')),
            ],
            options={
                'verbose_name_plural': 'book series',
                'db_table': 'book_series',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ManyToManyField(related_name='books', through='catalog.BookSeries', to='catalog.series'),
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order_index', models.PositiveIntegerField()),
                ('content_url', models.CharField(max_length=500)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='catalog.book')),
            ],
            options={
                'db_table': 'book_chapters',
                'ordering': ['book', 'order_index'],
                'constraints': [models.UniqueConstraint(fields=('book', 'order_index'), name='unique_chapter_order_per_book')],
            },
        ),
        migrations.CreateModel(
            name='EbookFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_drm_protected', models.BooleanField(default=False)),
                ('file_hash', models.CharField(blank=True, max_length=255)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, related_name='ebook_files', to='catalog.book')),
                ('format_type', models.ForeignKey(db_column='format_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='ebook_files', to='catalog.formattype')),
            ],
            options={
                'db_table': 'ebook_files',
                'ordering': ['book', 'format_type'],
                'unique_together': {('book', 'format_type')},
            },
        ),
        migrations.AddConstraint(
            model_name='bookseries',
            constraint=models.UniqueConstraint(fields=('book', 'series'), name='unique_book_series'),
        ),
        migrations.AddConstraint(
            model_name='bookseries',
            constraint=models.UniqueConstraint(fields=('series', 'volume_number'), name='unique_volume_per_series'),
        ),
    ]
