# Generated by Django 5.2.14 on 2026-06-05 10:18

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=catalog.models.book_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='ebookfile',
            name='file_url',
            field=models.FileField(max_length=500, upload_to=catalog.models.ebook_file_upload_to),
        ),
    ]
