# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_book_cover_image_alter_ebookfile_file_url"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE books "
                        "ADD COLUMN IF NOT EXISTS book_image jsonb NOT NULL "
                        "DEFAULT '{}'::jsonb"
                    ),
                    reverse_sql="ALTER TABLE books DROP COLUMN IF EXISTS book_image",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="book",
                    name="book_image",
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
        ),
    ]
