# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_book_book_image"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE books "
                        "ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL "
                        "DEFAULT true"
                    ),
                    reverse_sql="ALTER TABLE books DROP COLUMN IF EXISTS is_active",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="book",
                    name="is_active",
                    field=models.BooleanField(default=True),
                ),
            ],
        ),
    ]
