# Generated by Codex on 2026-06-06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_avatar_url"),
        ("catalog", "0004_book_is_active"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS book_reviews (
                        id serial PRIMARY KEY,
                        rating smallint NOT NULL,
                        comment text NOT NULL DEFAULT '',
                        created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        book_id integer NOT NULL,
                        customer_id integer NOT NULL
                    );

                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname = 'book_reviews_book_fk'
                        ) THEN
                            ALTER TABLE book_reviews
                            ADD CONSTRAINT book_reviews_book_fk
                            FOREIGN KEY (book_id)
                            REFERENCES books(id)
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname = 'book_reviews_customer_fk'
                        ) THEN
                            ALTER TABLE book_reviews
                            ADD CONSTRAINT book_reviews_customer_fk
                            FOREIGN KEY (customer_id)
                            REFERENCES customers(id)
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname = 'book_reviews_customer_book_unique'
                        ) THEN
                            ALTER TABLE book_reviews
                            ADD CONSTRAINT book_reviews_customer_book_unique
                            UNIQUE (customer_id, book_id);
                        END IF;
                    END $$;
                    """,
                    reverse_sql="DROP TABLE IF EXISTS book_reviews;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="BookReview",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "rating",
                            models.PositiveSmallIntegerField(
                                validators=[
                                    django.core.validators.MinValueValidator(1),
                                    django.core.validators.MaxValueValidator(5),
                                ],
                            ),
                        ),
                        ("comment", models.TextField(blank=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "book",
                            models.ForeignKey(
                                db_column="book_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="reviews",
                                to="catalog.book",
                            ),
                        ),
                        (
                            "customer",
                            models.ForeignKey(
                                db_column="customer_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="book_reviews",
                                to="accounts.customer",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "book_reviews",
                        "ordering": ["-updated_at"],
                        "unique_together": {("customer", "book")},
                    },
                ),
            ],
        ),
    ]
