# Generated by Codex on 2026-06-06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_bookreview"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_type WHERE typname = 'book_review_status'
                        ) THEN
                            CREATE TYPE book_review_status AS ENUM (
                                'pending',
                                'approved',
                                'rejected'
                            );
                        END IF;
                    END $$;

                    ALTER TABLE book_reviews
                    ALTER COLUMN rating TYPE integer USING rating::integer;

                    ALTER TABLE book_reviews
                    ADD COLUMN IF NOT EXISTS title varchar(255) NOT NULL DEFAULT '';

                    ALTER TABLE book_reviews
                    ADD COLUMN IF NOT EXISTS is_purchased boolean NOT NULL DEFAULT false;

                    ALTER TABLE book_reviews
                    ADD COLUMN IF NOT EXISTS status book_review_status NOT NULL DEFAULT 'approved';

                    ALTER TABLE book_reviews
                    DROP COLUMN IF EXISTS updated_at;
                    """,
                    reverse_sql="""
                    ALTER TABLE book_reviews
                    ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

                    ALTER TABLE book_reviews
                    DROP COLUMN IF EXISTS status;

                    DROP TYPE IF EXISTS book_review_status;

                    ALTER TABLE book_reviews
                    DROP COLUMN IF EXISTS is_purchased;

                    ALTER TABLE book_reviews
                    DROP COLUMN IF EXISTS title;

                    ALTER TABLE book_reviews
                    ALTER COLUMN rating TYPE smallint USING rating::smallint;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterModelOptions(
                    name="bookreview",
                    options={
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.AlterField(
                    model_name="bookreview",
                    name="rating",
                    field=models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                migrations.AddField(
                    model_name="bookreview",
                    name="title",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="bookreview",
                    name="is_purchased",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="bookreview",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                migrations.RemoveField(
                    model_name="bookreview",
                    name="updated_at",
                ),
            ],
        ),
    ]
