# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_align_bookreview_schema"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_enum e
                            JOIN pg_type t ON t.oid = e.enumtypid
                            WHERE t.typname = 'book_review_status'
                              AND e.enumlabel = 'reported'
                        ) THEN
                            ALTER TYPE book_review_status ADD VALUE 'reported';
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1 FROM pg_enum e
                            JOIN pg_type t ON t.oid = e.enumtypid
                            WHERE t.typname = 'book_review_status'
                              AND e.enumlabel = 'hidden'
                        ) THEN
                            ALTER TYPE book_review_status ADD VALUE 'hidden';
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1 FROM pg_enum e
                            JOIN pg_type t ON t.oid = e.enumtypid
                            WHERE t.typname = 'book_review_status'
                              AND e.enumlabel = 'deleted'
                        ) THEN
                            ALTER TYPE book_review_status ADD VALUE 'deleted';
                        END IF;
                    END $$;

                    UPDATE book_reviews SET title = '' WHERE title IS NULL;
                    UPDATE book_reviews SET comment = '' WHERE comment IS NULL;
                    UPDATE book_reviews SET is_purchased = false WHERE is_purchased IS NULL;
                    UPDATE book_reviews SET rating = 1 WHERE rating IS NULL;
                    UPDATE book_reviews SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
                    UPDATE book_reviews SET status = 'pending' WHERE status IS NULL;

                    ALTER TABLE book_reviews ALTER COLUMN customer_id SET NOT NULL;
                    ALTER TABLE book_reviews ALTER COLUMN book_id SET NOT NULL;
                    ALTER TABLE book_reviews ALTER COLUMN rating SET NOT NULL;
                    ALTER TABLE book_reviews ALTER COLUMN title SET NOT NULL;
                    ALTER TABLE book_reviews ALTER COLUMN comment SET NOT NULL;
                    ALTER TABLE book_reviews ALTER COLUMN is_purchased SET NOT NULL;
                    ALTER TABLE book_reviews ALTER COLUMN status SET NOT NULL;
                    ALTER TABLE book_reviews ALTER COLUMN created_at SET NOT NULL;

                    ALTER TABLE book_reviews ALTER COLUMN title SET DEFAULT '';
                    ALTER TABLE book_reviews ALTER COLUMN comment SET DEFAULT '';
                    ALTER TABLE book_reviews ALTER COLUMN is_purchased SET DEFAULT false;
                    ALTER TABLE book_reviews ALTER COLUMN status SET DEFAULT 'pending';
                    """,
                    reverse_sql="""
                    ALTER TABLE book_reviews ALTER COLUMN status SET DEFAULT 'approved';
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="bookreview",
                    name="comment",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AlterField(
                    model_name="bookreview",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("reported", "Reported"),
                            ("hidden", "Hidden"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
