# Generated by Django 5.2.14 on 2026-06-01 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='coupon',
            field=models.ForeignKey(blank=True, db_column='coupon_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promotions.coupon'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='order_status',
            field=models.ForeignKey(db_column='order_status', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='payment_method',
            field=models.ForeignKey(blank=True, db_column='payment_method_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.shoporder'),
        ),
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together={('order', 'book')},
        ),
    ]
