# Generated by Django 5.2.14 on 2026-06-01 09:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'promotions',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CouponBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_books', to='catalog.book')),
                ('coupon', models.ForeignKey(db_column='coupon_id', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_books', to='promotions.coupon')),
            ],
            options={
                'db_table': 'coupon_books',
                'unique_together': {('coupon', 'book')},
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='books',
            field=models.ManyToManyField(related_name='coupons', through='promotions.CouponBook', to='catalog.book'),
        ),
        migrations.CreateModel(
            name='CouponCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_categories', to='catalog.category')),
                ('coupon', models.ForeignKey(db_column='coupon_id', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_categories', to='promotions.coupon')),
            ],
            options={
                'verbose_name_plural': 'coupon categories',
                'db_table': 'coupon_categories',
                'unique_together': {('coupon', 'category')},
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(related_name='coupons', through='promotions.CouponCategory', to='catalog.category'),
        ),
        migrations.CreateModel(
            name='PromotionBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_books', to='catalog.book')),
                ('promotion', models.ForeignKey(db_column='promotion_id', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_books', to='promotions.promotion')),
            ],
            options={
                'db_table': 'promotion_books',
                'unique_together': {('promotion', 'book')},
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='books',
            field=models.ManyToManyField(related_name='promotions', through='promotions.PromotionBook', to='catalog.book'),
        ),
        migrations.CreateModel(
            name='PromotionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_categories', to='catalog.category')),
                ('promotion', models.ForeignKey(db_column='promotion_id', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_categories', to='promotions.promotion')),
            ],
            options={
                'verbose_name_plural': 'promotion categories',
                'db_table': 'promotion_categories',
                'unique_together': {('promotion', 'category')},
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(related_name='promotions', through='promotions.PromotionCategory', to='catalog.category'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('coupon', models.ForeignKey(db_column='coupon_id', on_delete=django.db.models.deletion.PROTECT, related_name='coupon_usages', to='promotions.coupon')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, related_name='coupon_usages', to='accounts.customer')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.shoporder')),
            ],
            options={
                'db_table': 'coupon_usages',
                'unique_together': {('order', 'coupon')},
            },
        ),
    ]
