# Generated by Django 5.2.14 on 2026-06-01 09:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'payment_types',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'transaction statuses',
                'db_table': 'transactions_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('expiry_day', models.DateField(blank=True, null=True)),
                ('cvv', models.CharField(blank=True, max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.customer')),
                ('payment_type', models.ForeignKey(db_column='payment_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='payments.paymenttype')),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_processed', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gateway_reference', models.CharField(blank=True, max_length=255)),
                ('gateway_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.shoporder')),
                ('payment_type', models.ForeignKey(db_column='payment_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymenttype')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.transactionstatus')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
